#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "VROSC/AudioReactive/AudioReactiveBehaviour.hpp"
#include "VROSC/AudioReactive/AudioReactiveCore.hpp"
#include "VROSC/AudioReactive/AudioReactiveCoreTester.hpp"
#include "VROSC/AudioReactive/AudioReactiveEffectData.hpp"
#include "VROSC/AudioReactive/AudioReactiveFilter.hpp"
#include "VROSC/AudioReactive/ChangeColorEffectData.hpp"
#include "VROSC/AudioReactive/CloudGlobalColors.hpp"
#include "VROSC/AudioReactive/ColorOnBeat.hpp"
#include "VROSC/AudioReactive/ConstantRotationData.hpp"
#include "VROSC/AudioReactive/CoroutineDrivenEffect.hpp"
#include "VROSC/AudioReactive/DrumpadEffect.hpp"
#include "VROSC/AudioReactive/EmitParticlesEffect.hpp"
#include "VROSC/AudioReactive/EmitParticlesEffectData.hpp"
#include "VROSC/AudioReactive/EmitParticlesOnBeat.hpp"
#include "VROSC/AudioReactive/GlobalColorEffectData.hpp"
#include "VROSC/AudioReactive/GlobalColorShiftEffect.hpp"
#include "VROSC/AudioReactive/GlobalColorShiftOnBeat.hpp"
#include "VROSC/AudioReactive/GlobalDrumOnBeat.hpp"
#include "VROSC/AudioReactive/GlobalShiftColorData.hpp"
#include "VROSC/AudioReactive/LerpColorEffect.hpp"
#include "VROSC/AudioReactive/ReactToBeat.hpp"
#include "VROSC/AudioReactive/ReactiveEffect.hpp"
#include "VROSC/AudioReactive/RotateEffect.hpp"
#include "VROSC/AudioReactive/RotateEffectData.hpp"
#include "VROSC/AudioReactive/RotateOnBeat.hpp"
#include "VROSC/AudioReactive/ScaleEffect.hpp"
#include "VROSC/AudioReactive/ScaleEffectData.hpp"
#include "VROSC/AudioReactive/ScaleOnBeat.hpp"
#include "VROSC/AudioReactive/ShaderEffect.hpp"
#include "VROSC/AudioReactive/ShaderEffectData.hpp"
#include "VROSC/AudioReactive/ShiftColorData.hpp"
#include "VROSC/AudioReactive/ShiftColorEffect.hpp"
#include "VROSC/AudioReactive/ShiftColorEffectData.hpp"
#include "VROSC/AudioReactive/SlowdownParticlesEffect.hpp"
#include "VROSC/AudioReactive/SlowdownParticlesEffectData.hpp"
#include "VROSC/AudioReactive/TransformEffectData.hpp"
#include "VROSC/AudioReactive/TransformLerpEffect.hpp"
#include "VROSC/AudioReactive/TransformOnBeat.hpp"
#include "VROSC/AudioReactive/TranslateEffect.hpp"
#include "VROSC/AudioReactive/TranslateEffectData.hpp"
#include "VROSC/AudioReactive/TranslateOnBeat.hpp"
#include "VROSC/AudioReactive/TriggerRotationData.hpp"
#ifdef __cpp_modules
                    export module AudioReactive;
                    #endif
                
