#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "Melanchall/DryWetMidi/Core/ChannelEvent.hpp"
#include "Melanchall/DryWetMidi/Core/ChannelEventWriter.hpp"
#include "Melanchall/DryWetMidi/Core/ChannelPrefixEvent.hpp"
#include "Melanchall/DryWetMidi/Core/ChunksCollection.hpp"
#include "Melanchall/DryWetMidi/Core/ChunksConverterFactory.hpp"
#include "Melanchall/DryWetMidi/Core/ControlChangeEvent.hpp"
#include "Melanchall/DryWetMidi/Core/EndOfTrackEvent.hpp"
#include "Melanchall/DryWetMidi/Core/EventTypesCollection.hpp"
#include "Melanchall/DryWetMidi/Core/EventWriterFactory.hpp"
#include "Melanchall/DryWetMidi/Core/EventsCollection.hpp"
#include "Melanchall/DryWetMidi/Core/FileUtilities.hpp"
#include "Melanchall/DryWetMidi/Core/HeaderChunk.hpp"
#include "Melanchall/DryWetMidi/Core/IChunksConverter.hpp"
#include "Melanchall/DryWetMidi/Core/IEventWriter.hpp"
#include "Melanchall/DryWetMidi/Core/KeySignatureEvent.hpp"
#include "Melanchall/DryWetMidi/Core/MetaEvent.hpp"
#include "Melanchall/DryWetMidi/Core/MetaEventWriter.hpp"
#include "Melanchall/DryWetMidi/Core/MidiChunk.hpp"
#include "Melanchall/DryWetMidi/Core/MidiEvent.hpp"
#include "Melanchall/DryWetMidi/Core/MidiEventType.hpp"
#include "Melanchall/DryWetMidi/Core/MidiFile.hpp"
#include "Melanchall/DryWetMidi/Core/MidiFileFormat.hpp"
#include "Melanchall/DryWetMidi/Core/MidiWriter.hpp"
#include "Melanchall/DryWetMidi/Core/MultiSequenceChunksConverter.hpp"
#include "Melanchall/DryWetMidi/Core/MultiTrackChunksConverter.hpp"
#include "Melanchall/DryWetMidi/Core/NoteEvent.hpp"
#include "Melanchall/DryWetMidi/Core/NoteOffEvent.hpp"
#include "Melanchall/DryWetMidi/Core/NoteOnEvent.hpp"
#include "Melanchall/DryWetMidi/Core/PitchBendEvent.hpp"
#include "Melanchall/DryWetMidi/Core/SequenceNumberEvent.hpp"
#include "Melanchall/DryWetMidi/Core/SetTempoEvent.hpp"
#include "Melanchall/DryWetMidi/Core/SingleTrackChunksConverter.hpp"
#include "Melanchall/DryWetMidi/Core/SmfConstants.hpp"
#include "Melanchall/DryWetMidi/Core/SysExEventWriter.hpp"
#include "Melanchall/DryWetMidi/Core/SystemCommonEvent.hpp"
#include "Melanchall/DryWetMidi/Core/SystemCommonEventWriter.hpp"
#include "Melanchall/DryWetMidi/Core/SystemRealTimeEvent.hpp"
#include "Melanchall/DryWetMidi/Core/SystemRealTimeEventWriter.hpp"
#include "Melanchall/DryWetMidi/Core/TicksPerQuarterNoteTimeDivision.hpp"
#include "Melanchall/DryWetMidi/Core/TimeDivision.hpp"
#include "Melanchall/DryWetMidi/Core/TimeSignatureEvent.hpp"
#include "Melanchall/DryWetMidi/Core/TooManyTrackChunksException.hpp"
#include "Melanchall/DryWetMidi/Core/TrackChunk.hpp"
#include "Melanchall/DryWetMidi/Core/UnknownChunk.hpp"
#include "Melanchall/DryWetMidi/Core/UnknownMetaEvent.hpp"
#include "Melanchall/DryWetMidi/Core/WriterSettings.hpp"
#include "Melanchall/DryWetMidi/Core/WritingSettings.hpp"
#ifdef __cpp_modules
                    export module Core;
                    #endif
                
