#ifdef __cpp_modules
                    module;
                    #endif
                
#pragma once
#include "System/IO/Compression/BlockType.hpp"
#include "System/IO/Compression/CheckSumAndSizeWriteStream.hpp"
#include "System/IO/Compression/CompressionLevel.hpp"
#include "System/IO/Compression/CompressionMode.hpp"
#include "System/IO/Compression/CopyEncoder.hpp"
#include "System/IO/Compression/Crc32Helper.hpp"
#include "System/IO/Compression/DeflateInput.hpp"
#include "System/IO/Compression/DeflateManagedStream.hpp"
#include "System/IO/Compression/DeflateStream.hpp"
#include "System/IO/Compression/DeflateStreamNative.hpp"
#include "System/IO/Compression/DeflaterManaged.hpp"
#include "System/IO/Compression/FastEncoder.hpp"
#include "System/IO/Compression/FastEncoderStatics.hpp"
#include "System/IO/Compression/FastEncoderWindow.hpp"
#include "System/IO/Compression/GZipStream.hpp"
#include "System/IO/Compression/HuffmanTree.hpp"
#include "System/IO/Compression/IFileFormatReader.hpp"
#include "System/IO/Compression/IFileFormatWriter.hpp"
#include "System/IO/Compression/InflaterManaged.hpp"
#include "System/IO/Compression/InflaterState.hpp"
#include "System/IO/Compression/InputBuffer.hpp"
#include "System/IO/Compression/Match.hpp"
#include "System/IO/Compression/MatchState.hpp"
#include "System/IO/Compression/OutputBuffer.hpp"
#include "System/IO/Compression/OutputWindow.hpp"
#include "System/IO/Compression/PositionPreservingWriteOnlyStreamWrapper.hpp"
#include "System/IO/Compression/SubReadStream.hpp"
#include "System/IO/Compression/WrappedStream.hpp"
#include "System/IO/Compression/Zip64EndOfCentralDirectoryLocator.hpp"
#include "System/IO/Compression/Zip64EndOfCentralDirectoryRecord.hpp"
#include "System/IO/Compression/Zip64ExtraField.hpp"
#include "System/IO/Compression/ZipArchive.hpp"
#include "System/IO/Compression/ZipArchiveEntry.hpp"
#include "System/IO/Compression/ZipArchiveMode.hpp"
#include "System/IO/Compression/ZipCentralDirectoryFileHeader.hpp"
#include "System/IO/Compression/ZipEndOfCentralDirectoryBlock.hpp"
#include "System/IO/Compression/ZipFile.hpp"
#include "System/IO/Compression/ZipFileExtensions.hpp"
#include "System/IO/Compression/ZipGenericExtraField.hpp"
#include "System/IO/Compression/ZipHelper.hpp"
#include "System/IO/Compression/ZipLocalFileHeader.hpp"
#include "System/IO/Compression/ZipVersionMadeByPlatform.hpp"
#include "System/IO/Compression/ZipVersionNeededValues.hpp"
#ifdef __cpp_modules
                    export module Compression;
                    #endif
                
